controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Revolute 1
      - Revolute 2
      - Revolute 4
      - Revolute 5
      - Revolute 6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: arm
    pose: default