arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Revolute 1
    - Revolute 2
    - Revolute 4
    - Revolute 5
    - Revolute 6
  gains:
    Revolute 1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Revolute 2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Revolute 4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Revolute 5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Revolute 6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1