arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     []
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10